[package]
name = "phonon-sys"
version = "0.1.0"
authors = ["Aceeri <conmcclusk@gmail.com>"]
edition = "2018"

[build-dependencies]
bindgen = "0.54.0"
wav = "0.4.0"

[dependencies]
libc = "0.2.71"
wav = "0.4.0"